- android/.gitignore
- android/app/build.gradle
- android/build.gradle
> firebaseにandroidアプリを構成する

- ios/.gitignore
> firebaseにiosアプリを構成する

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- lib/main.dart
- lib/register_page.dart
- lib/signin_page.dart
- pubspec.lock
- pubspec.yaml
> Firebase Authを使ってユーザを登録する

- android/app/build.gradle
- ios/Podfile.lock
- lib/register_page.dart
- pubspec.lock
- pubspec.yaml
#15
作成者：@kugimasa
テスター：@Yamakatsu63, @iHiromu 
手順 : ビルドしてユーザを**新規登録**し、Firestoreのデータを確認
データの確認は[コチラ](https://console.firebase.google.com/u/1/project/the4thday-of-mikkabozu/database/firestore/data~2Fuser~2Fw8kXtgtZI2Og8RLIKnCA)から
> Firestoreを導入します

- lib/main.dart
不要な画面の回転をなくすために縦に固定
作成者：@NishidaYujiro
テスター：@iHiromu,@daigo0907
@iHiromu
@daigo0907
> 画面の向きを縦に固定しました.

- lib/main.dart
- lib/register_page.dart
- lib/signin_page.dart
#49 
作成者：@tyanio
テスター：@kugimasa, @TakedaHiroki 
@kugimasa 
@TakedaHiroki
> ボタンがずれているのを直します

- lib/Screens/Home/home_manager.dart
- lib/Screens/Home/join_button.dart
- lib/Screens/Home/lookup_team.dart
#17 
作成者：@Yamakatsu63
テスター：@tyanio, @TakedaHiroki 
@tyanio
@TakedaHiroki
> チームを検索して参加する

- lib/Screens/Home/home_manager.dart
- lib/Screens/Home/join_button.dart
- lib/Screens/Home/lookup_team.dart
#(Issueの番号)
作成者：@tyanio
テスター：@Yamakatsu, @kugimasa
> フォーマットをかましてリファクタ前のメソッド名を直しました

- lib/Screens/Home/lookup_team.dart
- lib/Screens/Home/signout_button.dart
- lib/register_page.dart
- lib/signin_page.dart
- lib/teamcreate_page.dart
該当issue #63 
フィードバック文章を丁寧語に直します。
作成者：@Yamakatsu63
テスター：@tyanio, @kugimasa 
@tyanio
@kugimasa
> フィードバック文章の変更

- lib/Pages/MeasurementPage/measurement_page.dart
- lib/Pages/MyPage/home_manager.dart
- lib/Pages/MyPage/to_mesurement_page_button.dart
#14 
作成者：@NishidaYujiro
テスター：@tyanio, @Yamakatsu63, @daigo0907 
@tyanio
@Yamakatsu63
@daigo0907
> 計測ページを作成しました

- ios/Podfile.lock
- ios/Runner/Info.plist
- lib/Pages/MeasurementPage/measurement_page.dart
- pubspec.lock
- pubspec.yaml
#14 
作成者：@iHiromu
テスター：@TakedaHiroki , @NishidaYujiro, @tyanio 
iOS Simulator
- Latitude: `37.785834`
- Longitude: `-122.406417`
@TakedaHiroki
@NishidaYujiro
@tyanio
> 位置情報を取得して表示する

- lib/Pages/MeasurementPage/measurement_panel.dart
- lib/Pages/MyPage/SideMenu/sidemenu.dart
- lib/Pages/MyPage/home_manager.dart
- lib/Pages/TeamCreatePage/team_create_page.dart
#89, #94, #96, #97 
作成者：@Yamakatsu63
テスター：@tyanio, @daigo0907 , @iHiromu 
@tyanio 
@iHiromu 
@daigo0907
> Hotfix #89#94#96#97

- lib/Pages/LookupTeamPage/join_button.dart
- lib/Pages/LookupTeamPage/lookup_team_page.dart
- lib/Pages/MeasurementPage/measurement_button.dart
- lib/Pages/MeasurementPage/measurement_page.dart
- lib/Pages/MyPage/signin_screen.dart
- lib/Pages/TeamCreatePage/team_create_page.dart
- lib/SideMenu/sidemenu.dart
バックグラウンドでの距離計算
resolve #86
リファクタ&emailを`user_data.dart`から取る
resolve #93 
作成者：@kugimasa, @Yamakatsu63 
テスター：@iHiromu, @NishidaYujiro 
@iHiromu 
@NishidaYujiro
> バックグラウンドでの距離計算 & Issue#93(リファクタ)

- lib/Pages/LookupTeamPage/join_button.dart
- lib/Pages/MeasurementPage/measurement_page.dart
- lib/Pages/TeamCreatePage/team_create_page.dart
> ログイン時にドキュメントIDを取得する

- lib/PageView/page_view.dart
#99
作成者：@kugimasa
レビュワー：Weekly Scrumで合意を取れたら必要なし
> (Draft)タブメニューの表示名を変更

- lib/main.dart
作成者：@kugimasa
テスター：
@iHiromu
@NishidaYujiro
> debugラベルを外しました

- lib/Pages/LookupTeamPage/lookup_team_page.dart
作成者：@TakedaHiroki
テスター：@Yamakatsu63
> 部分一致でもチームを検索する

- lib/Pages/LookupTeamPage/lookup_team_page.dart
- lib/Pages/MeasurementPage/measurement_page.dart
> 同じ日付の記録をまとめて表示する

- lib/Pages/MyPage/my_page.dart
- pubspec.yaml
> 走った記録をカレンダーで表示する

- lib/SideMenu/sidemenu.dart
> Develop #31 create window

- lib/Pages/TeamCreatePage/team_create_page.dart
- lib/Pages/TeamPage/members_record.dart
> 週の記録の集計を日曜日の0時からに修正

- lib/Pages/MeasurementPage/measurement_page.dart
- lib/Pages/MeasurementPage/measurement_panel.dart
- lib/Pages/MyPage/my_page.dart
- lib/Pages/MyPage/records_screen.dart
#162 
作成者：@Yamakatsu63 , @NishidaYujiro 
テスター：
> 運動時間の計測ができる

- lib/Pages/ChatPage/char_page.dart
- lib/Pages/LookupTeamPage/lookup_team_page.dart
- lib/Pages/TeamPage/team_page.dart
#133
作成者：@Yamakatsu63, @NishidaYujiro
> チャット機能でチームメンバーと交流できる

- lib/Pages/TeamPage/team_page.dart
> Develop #167 leave team

- lib/SideMenu/sidemenu.dart
> サイドメニューをスタイルします

- lib/Pages/LookupTeamPage/lookup_team_page.dart
- lib/Pages/MyPage/records_screen.dart
- lib/Pages/TeamMainPage/team_main_page.dart
- lib/Pages/TeamPage/goal_manager.dart
- lib/Pages/TeamPage/members_record.dart
- lib/Pages/TeamPage/overview_manager.dart
- lib/Pages/TeamPage/team_page.dart
> Loadingと表示されていたところをグルグルにしました

- lib/Pages/TeamPage/members_record.dart
> 管理者権限を渡すしてページを戻ると先のダイアログが出てしまうのを直しました

- lib/SideMenu/sidemenu.dart
- lib/SideMenu/signout_button.dart
> サイドメニューをスタイリングしました

- lib/Pages/TeamMainPage/team_main_page.dart
| Before | After |
| :-- | :-- |
| ![Screenshot_1624498736](https://user-images.githubusercontent.com/19584781/123189285-82f43900-d4d8-11eb-8c6e-1203cd087be3.png) | ![Screenshot_1624498863](https://user-images.githubusercontent.com/19584781/123189376-b0d97d80-d4d8-11eb-84f3-4bc4b4aa15ca.png) |
> チーム一覧ページをスタイリングしました
